---
- name: Установка rsync на серверы
  hosts: webservers
  gather_facts: true
  become: true

  tasks:
    - name: Установка rsync на Debian/Ubuntu системы
      ansible.builtin.apt:
        name: rsync
        state: present
        update_cache: true
      when: ansible_os_family == "Debian"

    - name: Установка rsync на RedHat/CentOS/Rocky systems
      ansible.builtin.dnf:
        name: rsync
        state: present
        update_cache: true
      when: ansible_os_family == "RedHat"